### ISSUE TITLE
Evaluate gremlin usage

### ISSUE THREAD

**Issue by erlepereira** [RealQuestions/apiengine-v2#1]
python or php, using the new [openjdk docker image, with gremlin plugin](https://github.com/RealQuestions/dockerimages/tree/master/openjdk_neo4j)

[Gremlin Plugin](https://github.com/thinkaurelius/neo4j-gremlin-plugin/)

Store a single dataset, retrieve it. For this, just borrow the json structure used in one of the cypher queries. Maybe the [politicians api](https://github.com/RealQuestions/apiengine-v2/blob/master/politicians.php)

**Comment by worlddada** [comment]
Good luck.

**Comment by candronikos** [comment]
Hey Erle,

I set up a Titan container and managed to get this script running using [gremlinclient](https://github.com/davebshow/gremlinclient)'s websockets implementation.

I tested it by running it inside the container itself but should work outside if configured correctly.

Haven't gotten [aiogremlin](https://github.com/davebshow/aiogremlin) to work but I think this API is fine to use

```
#Working script using gremlinclient
#https://github.com/davebshow/gremlinclient
import asyncio
from tornado.platform.asyncio import AsyncIOMainLoop
from gremlinclient import aiosubmit
AsyncIOMainLoop().install() # Use the asyncio event loop
loop = asyncio.get_event_loop()
@asyncio.coroutine
def go():
    resp = yield from aiosubmit("1 + 5")
    while True:
        msg = yield from resp.read()
        if msg is None:
            break
        #print(msg)
        print("Result: %d" % msg.data[0])
loop.run_until_complete(go())
```

Still haven't gotten around that PHAR error I'm getting with PHP.

**Comment by erlepereira** [comment]
Thanks Chris, closing this issue here. This gives us what we need. Might reopen later for added investigation if needed.
